apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7CgkJCSJhdXRoIjogIlZWTkZVazVCVFVVNloyaDFYMWgyWkZBM1dFeEZRMDV0TWpGNloyYzRNVFZ1Vm05V2RWSlpWakowYlROV1kxWjJaUT09IgoJCX0sCgkJImdoY3IuaW8iOiB7CgkJCSJhdXRoIjogIlFXeHBibUZUYUdsc09tZG9jRjk0TjBzNWMwSlBRMFZvWm1SR1JHcExTRk5sUTB4M1puVnhkRnBVYUZFd2NtODJRME09IgoJCX0sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsKCQkJImF1dGgiOiAiWTI5a1pYTndZV05sYzJSbGRqcGtaakJsWlRaaFpDMW1PV0l5TFRReU0yTXRPRGM0WmkwMk16VmtNR001TkdSall6ST0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiWC1NZXRhLVNvdXJjZS1DbGllbnQiOiAiZ2l0aHViL2NvZGVzcGFjZXMiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
